### PR TITLE
Improve page range calculation

### PR DESCRIPTION
**Pull request by jerbob92**
Add unit tests to test for #5 
Fixes a bug where not all pages were added

### CODE REVIEW

**Comment by jerbob92** [comment]
@msageryd I could not reproduce your bug but I did find another that is fixed by this, also added unit tests.
Which command did you execute exactly?

**Comment by msageryd** [comment]
This is the command I'm using on a 20 page PDF:

`pdfion-cli explode --pages '1,2,5-22' --std-file-delimiter '--9c354adf-6110-4016-aae7-e48740e7192c' - -`

If I back down to 20
 it works.
`pdfion-cli explode --pages '1,2,5-20' --std-file-delimiter '--9c354adf-6110-4016-aae7-e48740e7192c' - -`

This is the PDF I'm using in my test suite.
[oh-shit-git-zine.pdf](https://github.com/klippa-app/pdfium-cli/files/12718870/oh-shit-git-zine.pdf)

**Comment by jerbob92** [comment]
For me that command works fine and results in 
> invalid page range '1,2,5-22': 22 is not a valid page number, the document has 20 page(s)

**Comment by msageryd** [comment]
Aha, I see now. It was my fault.
I thought I'd receive the error code (6) as "process exit code" after the process ended. But the only way to see the error is via stderr. I have now reversed the check, so I check stderr before checking the exit code, so I'll catch the correct error.

Do you plan to add exit codes to pdfium-cli? pdftocairo does this, and it's quite convenient. Error strings are not as easy to take action on, since you either have to trust them to never change, or parse them if they have an error code embedded.

**Comment by jerbob92** [comment]
Sure, do they do different codes per error, or just one code to tell you something went wrong?

**Comment by msageryd** [comment]
Cairo sends error code as per Popplers documentation.

In Pdfiums case I suppose these should be used:
0 no error
1 unknown error
2 file not found or could not be opened
3 file not in PDF format or corrupted
4 password required or incorrect password
5 unsupported security scheme
6 page not found or content error

**Comment by jerbob92** [comment]
I have added the exit codes here: #12
You can find the codes here: https://github.com/klippa-app/pdfium-cli/blob/main/cmd/exit_codes.go
The errors codes are more than what pdfium can return, but the pdfium specific errors are properly mapped to ExitCodePdfium*

**Pull request merged**
